name: datafusion-project

services:
  app:
    build:
      context: ../../
      dockerfile: .tools/docker/Dockerfile
    container_name: datafusion-app
    environment:
      - DISPLAY=${DISPLAY:-:0}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Baza i dane wejsciowe wspoldzielone z hostem.
      - ../../database:/app/database
    network_mode: host
